<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Dracula.ManagedHost</RootNamespace>
    <AssemblyName>Dracula.ManagedHost</AssemblyName>
    <PublishSingleFile>false</PublishSingleFile>
  </PropertyGroup>

</Project>
