# ─── Artwork embedding ──────────────────────────────────────────────────────
#
# "Vampire Dracula ASCII Art.txt" in the project root is the single editable
# source of truth for the Dracula terminal artwork. This step reads that file at
# configure time and generates a C++ header holding its bytes as explicit \xNN
# escapes, which is then compiled into the executable.
#
# Two properties matter here:
#
#   * A released Dracula.exe has NO runtime dependency on the .txt file or on
#     any absolute path - the artwork lives in the binary.
#   * The bytes survive the build pipeline exactly. Escaping every byte means no
#     source encoding, codepage or editor normalisation can silently alter the
#     Braille glyphs on their way into the compiler.
#
# dracula_embed_art(<input .txt> <output .h>)
#
function(dracula_embed_art ART_INPUT ART_OUTPUT)
    if(NOT EXISTS "${ART_INPUT}")
        message(FATAL_ERROR "Dracula artwork source not found: ${ART_INPUT}")
    endif()

    # Re-run CMake when the artwork is edited, so the generated header and the
    # .txt can never drift apart.
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${ART_INPUT}")

    file(READ "${ART_INPUT}" ART_HEX HEX)
    string(LENGTH "${ART_HEX}" ART_HEX_LENGTH)
    math(EXPR ART_BYTE_COUNT "${ART_HEX_LENGTH} / 2")

    set(ART_ROWS "")          # completed rows, each already escaped
    set(ART_CURRENT "")       # row under construction
    set(ART_ROW_COUNT 0)

    math(EXPR ART_LAST "${ART_BYTE_COUNT} - 1")
    foreach(INDEX RANGE 0 ${ART_LAST})
        math(EXPR OFFSET "${INDEX} * 2")
        string(SUBSTRING "${ART_HEX}" ${OFFSET} 2 BYTE)

        if(BYTE STREQUAL "0a")
            # End of row. A CR was already dropped below, so nothing to strip.
            list(APPEND ART_ROWS "${ART_CURRENT}")
            math(EXPR ART_ROW_COUNT "${ART_ROW_COUNT} + 1")
            set(ART_CURRENT "")
        elseif(BYTE STREQUAL "0d")
            # CRLF and CR line endings both terminate on the following byte.
        else()
            string(APPEND ART_CURRENT "\\x${BYTE}")
        endif()
    endforeach()

    # A final row without a trailing newline is still a row.
    if(NOT ART_CURRENT STREQUAL "")
        list(APPEND ART_ROWS "${ART_CURRENT}")
        math(EXPR ART_ROW_COUNT "${ART_ROW_COUNT} + 1")
    endif()

    if(ART_ROW_COUNT EQUAL 0)
        message(FATAL_ERROR "Dracula artwork source is empty: ${ART_INPUT}")
    endif()

    get_filename_component(ART_NAME "${ART_INPUT}" NAME)

    set(ART_BODY "")
    foreach(ROW IN LISTS ART_ROWS)
        string(APPEND ART_BODY "        \"${ROW}\",\n")
    endforeach()

    set(ART_GENERATED
"#pragma once

//
// GENERATED FILE - DO NOT EDIT.
//
// Generated by cmake/EmbedArt.cmake from the project asset:
//     ${ART_NAME}
//
// Edit that file to change the Dracula artwork; CMake regenerates this header
// automatically. Every byte is escaped so the artwork cannot be altered by a
// source encoding or codepage conversion on its way into the compiler.
//

namespace Dracula {
namespace Art {
namespace Embedded {

    // Rows exactly as they appear in the source asset, without line endings.
    inline constexpr const char* const kVampireRows[] = {
${ART_BODY}    };

    inline constexpr int kVampireRowCount = ${ART_ROW_COUNT};

} // namespace Embedded
} // namespace Art
} // namespace Dracula
")

    get_filename_component(ART_OUTPUT_DIR "${ART_OUTPUT}" DIRECTORY)
    file(MAKE_DIRECTORY "${ART_OUTPUT_DIR}")

    # Only rewrite when the content actually changes, so an unchanged artwork
    # does not force a rebuild of everything that includes the header.
    if(EXISTS "${ART_OUTPUT}")
        file(READ "${ART_OUTPUT}" ART_EXISTING)
    else()
        set(ART_EXISTING "")
    endif()
    if(NOT ART_EXISTING STREQUAL "${ART_GENERATED}")
        file(WRITE "${ART_OUTPUT}" "${ART_GENERATED}")
    endif()

    message(STATUS "Dracula artwork embedded: ${ART_NAME} (${ART_ROW_COUNT} rows, ${ART_BYTE_COUNT} bytes)")
endfunction()
